version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/os_lab4_db
      SPRING_DATASOURCE_USERNAME: "my_user"
      SPRING_DATASOURCE_PASSWORD: "password"
    ports:
     - 8080:8080
          
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=os_lab4_db
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=password
    ports:
      - 3307:3306
